# navigation with C-{h,j,k,l} -- NO PREFIX
# https://gist.github.com/mislav/5189704

set -g xterm-keys on
## See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l" Smart pane switching with awareness of vim splits
#setw -g mode-keys vi
#bind -n C-k run-shell 'tmux-vim-select-pane -U'
#bind -n C-j run-shell 'tmux-vim-select-pane -D'
#bind -n C-h run-shell 'tmux-vim-select-pane -L

###########################################################################
# to have sane pane navigation in nvim
nnoremap <silent> <BS> :TmuxNavigateLeft<cr>
###########################################################################
# to get proper colors with vim in tmux
set -g default-terminal "xterm-256color"

###########################################################################
# Scrollback / pastebuffer

# Vim-style copy/paste
unbind [
    bind y copy-mode
    unbind p
    bind p paste-buffer
    bind -t vi-copy v begin-selection
    bind -t vi-copy y copy-selection

###########################################################################
# Mouse mode

    set -g mode-mouse on
    set -g mouse-resize-pane on
    set -g mouse-select-pane on
    set -g mouse-select-window on

###########################################################################
# Pane management / navigation

# Horizontal splits with s or C-s
    unbind s
    unbind C-s
    bind-key s split-window
    bind-key C-s split-window

# Vertical split with v or C-v
    unbind v
    unbind C-v
    bind-key v split-window -h
    bind-key C-v split-window -h

#set-option -g status-right "#(~/.tmux-powerline/powerline.sh right)"


#    set-window-option -g window-status-current-format "#[fg=colour235, bg=colour27]⮀#[fg=colour255, bg=colour27] #I ⮁ #W #[fg=colour27, bg=colour235]⮀"




